server:
  port: 8190
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      routes:
        - id: customers
          uri: lb://customers-service
          predicates:
            - Path=/api/customers,/api/customers/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/v1
            
        - id: bootcoin-quote
          uri: lb://bootcoin-quote
          predicates:
            - Path=/bootcoin/quote/**
          filters:
            - RewritePath=/bootcoin/quote/(?<seg>.*),/api/v1/bootcoin/quote/${seg}
            
        - id: accounts
          uri: lb://account-service
          predicates:
            - Path=/api/accounts,/api/accounts/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api
        

        - id: cards
          uri: lb://cards-service
          predicates:
            - Path=/api/cards,/api/cards/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api

        - id: wallet-payments
          uri: lb://wallet-payments-service
          predicates:
            - Path=/api/wallet-payments,/api/wallet-payments/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api

        - id: credits
          uri: lb://credits-service
          predicates:
            - Path=/api/credits,/api/credits/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/v1
            
        - id: wallet
          uri: lb://wallet-service
          predicates:
            - Path=/api/wallets,/api/wallets/**
          filters:
            - StripPrefix=1      
