server:
  port: 8190
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      routes:
        - id: customers
          uri: lb://customers-service
          predicates:
            - Path=/api/customers,/api/customers/**
          filters:
              - StripPrefix=1
              - PrefixPath=/api/v1
        - id: authorization-server
          uri: lb://authorization-server
          predicates:
            - Path=/api/security/**
          filters:
              - StripPrefix=2
       - id: accounts
          uri: lb://account-service
          predicates:
            - Path=/api/accounts,/api/accounts/**
          filters:
              - StripPrefix=1
              - PrefixPath=/api/v1
         
