server:
  port: 8095

spring:
  application:
    name: bootocoin-quote

  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
        request.timeout.ms: 20000
        delivery.timeout.ms: 30000

  redis:
    host: redis
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms

  jackson:
    serialization:
      write-dates-as-timestamps: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/nttdatabank

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
    fetchRegistry: true
    registerWithEureka: true
  instance:
    prefer-ip-address: true
    hostname: bootocoin-quote
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

app:
  topics:
    quote-updated: quote.updated
  security:
    required-scope: Partners
